### ISSUE TITLE
Add tests to contracts

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/example-contracts#14]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/example-contracts/issues/132
- [ ] https://github.com/zeta-chain/example-contracts/issues/133
- [ ] https://github.com/zeta-chain/example-contracts/issues/134
- [ ] https://github.com/zeta-chain/example-contracts/issues/135
- [ ] https://github.com/zeta-chain/example-contracts/issues/136
- [ ] https://github.com/zeta-chain/example-contracts/issues/137
- [ ] https://github.com/zeta-chain/example-contracts/issues/138
- [ ] https://github.com/zeta-chain/example-contracts/issues/139
```

**Comment by fadeev** [comment]
For reference we can use tests from the app contracts repo:

https://github.com/zeta-chain/zetachain/blob/main/packages/zeta-app-contracts/test/MultiChainValue.spec.ts

https://github.com/zeta-chain/zetachain/tree/main/packages/zevm-app-contracts/test

**Comment by fadeev** [comment]
If we need any reusable code, we can add it to the toolkit.

**Comment by fadeev** [comment]
There is also an example in this PR: https://github.com/zeta-chain/example-contracts/pull/113
